### PR TITLE
chore: fix bad merge of bump/v4.25.0

### PR DESCRIPTION
**Pull request by kim-em**
See [#mathlib4 > compilation error on master? @ 💬](https://leanprover.zulipchat.com/#narrow/channel/287929-mathlib4/topic/compilation.20error.20on.20master.3F/near/546193405)

### CODE REVIEW

**Comment by kim-em** [comment]
bors p=100

**Comment by kim-em** [comment]
bors merge
